[phases.setup]
nixPkgs = ["nodejs_18", "nodejs", "yarn", "gcc"]
aptPkgs = ["git", "curl"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm rebuild"]

[start]
cmd = "cd backend && node index.js"