[http]
# Direct proxy configuration for Railway
port = 8080

# Enable health checks
[http.health_checks]
path = "/health"
interval = "15s"
timeout = "5s"
max_failures = 3

# Configure proxy timeouts
[http.timeouts]
read = "30s"
write = "30s"
idle = "60s"

# Access control settings
[http.cors]
enabled = true
allow_origins = ["*"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]
allow_headers = ["*"]
expose_headers = ["*"]
allow_credentials = true
max_age = 86400